name: flutter_inset_shadow
description: This package extends BoxShadow and BoxDecoration to support the inset property.
version: 2.0.3
repository: https://github.com/chitochi/flutter_inset_shadow

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

environment:
  flutter: '>=3.32.0'
  sdk: '>=3.8.0 <4.0.0'
